---
- name: copy some music
  copy:
      src: "{{ music_dir_host }}"
      dest: /opt/music
      force: no
  when: music_dir_host is defined

- name: install ympd dependencies + mpd
  apt:
      name: ['g++', 'cmake', 'libmpdclient-dev', 'git', 'build-essential', 'openssl', 'libssl-dev', 'mpd', 'mpc']
      state: present

- name: remove mpds default music dir
  file:
      dest: /var/lib/mpd/music
      state: absent

- name: create folder for music
  file:
      path: "{{ music_dir }}"
      state: directory
      mode: 0755
      owner: mpd

- name: link music
  file:
      src: "{{ music_dir }}" 
      dest: /var/lib/mpd/music
      state: link

- name: start mpd
  service:
      name: mpd
      state: restarted
      enabled: true

# end mpd and start with ympd

- name: clone ympd git repo
  git:
      repo: https://github.com/notandy/ympd
      dest: /opt/ympd/
      version: v1.3.0
      force: true

- name: add ympd patch file
  copy: 
    src: fix_header.patch
    dest: /tmp/fix_header.patch

- name: patch ympd index.html
  shell: patch -p 1 < /tmp/fix_header.patch
  args:
    chdir: /opt/ympd

- name: run make
  command: cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr
  args:
    chdir: /opt/ympd/src

- name: run make install
  command: make install
  args:
    chdir: /opt/ympd/src

- name: copy systemd service file
  copy:
      src: ympd.service
      dest: /etc/systemd/system/ympd.service

- name: reload services
  systemd:
      daemon_reload: true

- name: start ympd
  service:
      name: ympd
      state: restarted
      enabled: true

- name: update mpd database
  shell: mpc update
